// _backup_nextjs/src/app/[tenant_slug]/dashboard/page.tsx
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-gray-900">Dashboard Overview</h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Total Employees</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold text-blue-600">124</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Departments</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold text-blue-600">8</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Active Roles</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl font-bold text-blue-600">5</p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// pages/[tenant_slug]/dashboard/index.vue
<script setup lang="ts">
definePageMeta({
  layout: 'dashboard'
})
</script>

<template>
  <div class="space-y-6">
    <h2 class="text-2xl font-bold text-gray-900">Dashboard Overview</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <UiCard>
        <UiCardHeader>
          <UiCardTitle>Total Employees</UiCardTitle>
        </UiCardHeader>
        <UiCardContent>
          <p class="text-3xl font-bold text-brand-navy">124</p>
        </UiCardContent>
      </UiCard>
      <UiCard>
        <UiCardHeader>
          <UiCardTitle>Departments</UiCardTitle>
        </UiCardHeader>
        <UiCardContent>
          <p class="text-3xl font-bold text-brand-navy">8</p>
        </UiCardContent>
      </UiCard>
      <UiCard>
        <UiCardHeader>
          <UiCardTitle>Active Roles</UiCardTitle>
        </UiCardHeader>
        <UiCardContent>
          <p class="text-3xl font-bold text-brand-navy">5</p>
        </UiCardContent>
      </UiCard>
    </div>
  </div>
</template>
