// _backup_nextjs/src/app/[tenant_slug]/dashboard/payroll/create/page.tsx
'use client';

import React from 'react';
import CreatePayrollForm from '@/components/payroll/CreatePayrollForm';
import { PayrollService } from '@/services/payroll.service';
import { CreatePayrollRequest } from '@/types/payroll';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter, useParams } from 'next/navigation';
import { toast } from 'react-hot-toast';
import { ChevronLeft } from 'lucide-react';
import { Button } from '@/components/ui/Button';

export default function CreatePayrollPage() {
  const router = useRouter();
  const params = useParams();
  const tenantSlug = params?.tenant_slug as string;
  const queryClient = useQueryClient();

  const createMutation = useMutation({
    mutationFn: (data: CreatePayrollRequest) => PayrollService.createPayroll(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['payrolls'] });
      queryClient.invalidateQueries({ queryKey: ['payroll-summary'] });
      toast.success('Payroll created successfully');
      router.push(`/${tenantSlug}/dashboard/payroll`);
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    onError: (error: any) => {
      toast.error(error?.response?.data?.message || 'Failed to create payroll');
    }
  });

  const handleSubmit = async (data: CreatePayrollRequest) => {
    await createMutation.mutateAsync(data);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-4">
        <Button variant="ghost" onClick={() => router.back()} className="p-2">
          <ChevronLeft className="h-5 w-5" />
        </Button>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Create New Payroll</h1>
          <p className="text-gray-500">Calculate and generate payroll for an employee.</p>
        </div>
      </div>

      <CreatePayrollForm 
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}

// pages/[tenant_slug]/dashboard/payroll/create.vue
<script setup lang="ts">
import CreatePayrollForm from '@/components/payroll/CreatePayrollForm.vue'
import { ArrowLeft } from 'lucide-vue-next'

definePageMeta({
  layout: 'dashboard'
})

const router = useRouter()

const handleSuccess = () => {
    router.push({ path: '.' }) // Go back to index
}

const handleCancel = () => {
    router.back()
}
</script>

<template>
    <div class="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="md:flex md:items-center md:justify-between">
            <div class="flex items-center min-w-0">
                <button @click="handleCancel" class="mr-4 text-gray-400 hover:text-gray-500">
                    <ArrowLeft class="w-6 h-6" />
                </button>
                <div>
                    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                        Create New Payroll
                    </h2>
                    <p class="mt-1 text-sm text-gray-500">
                        Calculate salary and generate payroll entry
                    </p>
                </div>
            </div>
        </div>

        <CreatePayrollForm 
            @success="handleSuccess"
            @cancel="handleCancel"
        />
    </div>
</template>
