// _backup_nextjs/src/app/[tenant_slug]/dashboard/employees/create/page.tsx
'use client';

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useCreateEmployee } from '@/hooks/useEmployees';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { useRouter } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';

const employeeSchema = z.object({
  firstName: z.string().min(2, 'First Name must be at least 2 characters'),
  lastName: z.string().min(2, 'Last Name must be at least 2 characters'),
  email: z.string().email('Invalid email address'),
  password: z.string().min(6, 'Password must be at least 6 characters'),
  position: z.string().min(2, 'Position is required'),
  department: z.string().min(2, 'Department is required'),
  joinDate: z.string().refine((val) => !isNaN(Date.parse(val)), 'Invalid date'),
  baseSalary: z.coerce.number().min(0, 'Salary must be positive'),
});

type EmployeeFormValues = z.infer<typeof employeeSchema>;

export default function CreateEmployeePage() {
  const router = useRouter();
  const { mutate: createEmployee, isPending } = useCreateEmployee();
  
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<EmployeeFormValues>({
    resolver: zodResolver(employeeSchema) as any,
  });

  const onSubmit = (data: EmployeeFormValues) => {
    // Ensure joinDate is in ISO format if input is date
    const payload = {
      ...data,
      joinDate: new Date(data.joinDate).toISOString(),
    };
    createEmployee(payload);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-4">
        <Button variant="ghost" onClick={() => router.back()}>
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>
        <h2 className="text-2xl font-bold text-gray-900">Add New Employee</h2>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Employee Details</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Input
                label="First Name"
                error={errors.firstName?.message}
                {...register('firstName')}
              />
              <Input
                label="Last Name"
                error={errors.lastName?.message}
                {...register('lastName')}
              />
              <Input
                label="Email Address"
                type="email"
                error={errors.email?.message}
                {...register('email')}
              />
              <Input
                label="Password"
                type="password"
                error={errors.password?.message}
                {...register('password')}
              />
              <Input
                label="Position"
                error={errors.position?.message}
                {...register('position')}
              />
              <Input
                label="Department"
                error={errors.department?.message}
                {...register('department')}
              />
              <Input
                label="Join Date"
                type="date"
                error={errors.joinDate?.message}
                {...register('joinDate')}
              />
              <Input
                label="Base Salary"
                type="number"
                error={errors.baseSalary?.message}
                {...register('baseSalary')}
              />
            </div>

            <div className="flex justify-end space-x-4">
              <Button type="button" variant="secondary" onClick={() => router.back()}>
                Cancel
              </Button>
              <Button type="submit" isLoading={isPending}>
                Create Employee
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// pages/[tenant_slug]/dashboard/employees/create/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { ArrowLeft } from 'lucide-vue-next'
import type { CreateEmployeePayload } from '@/types/employee'

const route = useRoute()
const router = useRouter()
const tenantSlug = route.params.tenant_slug as string

definePageMeta({
  layout: 'dashboard'
})

const { mutate: createEmployee, loading } = useCreateEmployee()

const form = ref<CreateEmployeePayload>({
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  position: '',
  department: '',
  joinDate: '',
  baseSalary: 0
})

const goBack = () => {
  router.push(`/${tenantSlug}/dashboard/employees`)
}

const handleSubmit = async () => {
  if (!form.value.firstName || !form.value.lastName || !form.value.email || !form.value.password || !form.value.position || !form.value.department || !form.value.joinDate) {
    alert('Please fill in all required fields')
    return
  }

  // Ensure joinDate is ISO
  const payload = {
    ...form.value,
    joinDate: new Date(form.value.joinDate).toISOString()
  }

  try {
    await createEmployee(payload)
    // Maybe show success?
    goBack()
  } catch (e) {
    console.error(e)
    alert('Failed to create employee')
  }
}
</script>

<template>
  <div class="space-y-6 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="flex items-center space-x-4">
      <UiButton variant="ghost" @click="goBack">
        <ArrowLeft class="w-4 h-4 mr-2" />
        Back
      </UiButton>
      <h2 class="text-2xl font-bold text-gray-900">Add New Employee</h2>
    </div>

    <UiCard>
      <UiCardHeader>
        <UiCardTitle>Employee Details</UiCardTitle>
      </UiCardHeader>
      <UiCardContent>
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <UiInput
              label="First Name"
              v-model="form.firstName"
              required
            />
            <UiInput
              label="Last Name"
              v-model="form.lastName"
              required
            />
            <UiInput
              label="Email Address"
              type="email"
              v-model="form.email"
              required
            />
            <UiInput
              label="Password"
              type="password"
              v-model="form.password"
              required
            />
            <UiInput
              label="Position"
              v-model="form.position"
              required
            />
            <UiInput
              label="Department"
              v-model="form.department"
              required
            />
            <UiInput
              label="Join Date"
              type="date"
              v-model="form.joinDate"
              required
            />
            <UiInput
              label="Base Salary"
              type="number"
              v-model="form.baseSalary"
              required
            />
          </div>

          <div class="flex justify-end space-x-4">
            <UiButton type="button" variant="secondary" @click="goBack">
              Cancel
            </UiButton>
            <UiButton type="submit" :disabled="loading">
              {{ loading ? 'Creating...' : 'Create Employee' }}
            </UiButton>
          </div>
        </form>
      </UiCardContent>
    </UiCard>
  </div>
</template>
