// src/components/settings/AttendanceMap.tsx
'use client';

import { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Marker, Circle, useMapEvents, useMap } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

const DefaultIcon = L.icon({
  iconUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png',
  shadowUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-shadow.png',
  iconSize: [25, 41],
  iconAnchor: [12, 41],
});
L.Marker.prototype.options.icon = DefaultIcon;

interface AttendanceMapProps {
  latitude: number;
  longitude: number;
  radius: number;
  onLocationSelect: (lat: number, lng: number) => void;
}

function LocationMarker({ 
  position, 
  onLocationSelect 
}: { 
  position: [number, number], 
  onLocationSelect: (lat: number, lng: number) => void 
}) {
  useMapEvents({
    click(e) {
      onLocationSelect(e.latlng.lat, e.latlng.lng);
    },
  });

  return position ? <Marker position={position} /> : null;
}

function MapUpdater({ center }: { center: [number, number] }) {
  const map = useMap();
  useEffect(() => {
    if (center) {
      map.setView(center, map.getZoom());
    }
  }, [center, map]);
  return null;
}

export default function AttendanceMap({
  latitude,
  longitude,
  radius,
  onLocationSelect,
}: AttendanceMapProps) {
  // Default to Jakarta if 0,0 provided or invalid
  const hasLocation = !!(latitude && longitude);
  const centerPosition: [number, number] = hasLocation 
    ? [latitude, longitude] 
    : [-6.2088, 106.8456];

  const [position, setPosition] = useState<[number, number]>(centerPosition);

  const [pendingLocation, setPendingLocation] = useState<[number, number] | null>(null);



  const handleMapClick = (lat: number, lng: number) => {
    setPendingLocation([lat, lng]);
  };

  const confirmLocation = () => {
    if (pendingLocation) {
      setPosition(pendingLocation);
      onLocationSelect(pendingLocation[0], pendingLocation[1]);
      setPendingLocation(null);
    }
  };

  const cancelLocation = () => {
    setPendingLocation(null);
  };

  return (
    <div className="space-y-4 relative">
      <div className="h-[400px] w-full rounded-lg overflow-hidden border border-gray-300 relative z-0">
        <MapContainer 
          center={centerPosition} 
          zoom={15} 
          scrollWheelZoom={true} 
          style={{ height: '100%', width: '100%' }}
        >
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <MapUpdater center={pendingLocation || position} />
          <LocationMarker position={pendingLocation || position} onLocationSelect={handleMapClick} />
          {/* Show visual circle for current saved position if not pending, or pending if intent is to show what it would look like */}
          <Circle center={pendingLocation || position} radius={radius} pathOptions={{ color: pendingLocation ? 'orange' : 'blue' }}/>
        </MapContainer>

        {/* Confirmation Modal Overlay */}
        {pendingLocation && (
          <div className="absolute inset-0 z-[1000] flex items-end justify-center pb-6 bg-black/10 pointer-events-none">
             <div className="bg-white p-4 rounded-lg shadow-lg pointer-events-auto flex flex-col items-center gap-3 animate-in fade-in slide-in-from-bottom-4">
                <p className="text-sm font-medium text-gray-900">Update Check Point Location?</p>
                <div className="flex gap-2">
                  <button 
                    onClick={cancelLocation}
                    className="px-3 py-1.5 text-xs font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md transition-colors"
                  >
                    Cancel
                  </button>
                  <button 
                    onClick={confirmLocation}
                    className="px-3 py-1.5 text-xs font-medium text-white bg-brand-navy hover:opacity-90 rounded-md transition-colors"
                  >
                    Save Location
                  </button>
                </div>
             </div>
          </div>
        )}
      </div>
      <p className="text-xs text-gray-500">
        Click on the map to set the attendance check-point center. You will be asked to confirm.
      </p>
    </div>
  );
}

// components/settings/AttendanceMap.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { LMap, LTileLayer, LMarker, LCircle } from "@vue-leaflet/vue-leaflet";
import "leaflet/dist/leaflet.css";

// Dynamic import for Leaflet to avoid SSR issues
const L = ref<any>(null)

onMounted(async () => {
    // Fix Leaflet's default icon path issues with webpack/vite
    const leaflet = await import('leaflet');
    L.value = leaflet.default || leaflet;
    
    // Fix icons
    delete (L.value.Icon.Default.prototype as any)._getIconUrl;
    L.value.Icon.Default.mergeOptions({
        iconRetinaUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon-2x.png',
        iconUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png',
        shadowUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-shadow.png',
    });
});

const props = defineProps<{
  latitude: number;
  longitude: number;
  radius: number;
}>()

const emit = defineEmits<{
  (e: 'locationSelect', lat: number, lng: number): void
}>()

const zoom = ref(15)
const hasLocation = computed(() => !!(props.latitude && props.longitude))

// Internal position state that syncs with props but can be optimistic
const currentPosition = ref<[number, number]>(
    hasLocation.value ? [props.latitude, props.longitude] : [-6.2088, 106.8456]
)

// Sync with props when they change
watch(() => [props.latitude, props.longitude], ([newLat, newLng]) => {
     if (newLat && newLng) {
         currentPosition.value = [newLat, newLng]
         // Also verify center isn't too far? Optional.
     }
})

const pendingLocation = ref<[number, number] | null>(null)
const center = ref<[number, number]>(currentPosition.value)

// Keep center in sync with currentPosition primarily
watch(currentPosition, (newPos) => {
    if (!pendingLocation.value) {
        center.value = newPos
    }
})

const onMapClick = (e: any) => {
    // e.latlng contains lat and lng
    if (e.latlng) {
        pendingLocation.value = [e.latlng.lat, e.latlng.lng]
        // Center view on click? maybe not forced, but let's do it for visibility
        // center.value = [e.latlng.lat, e.latlng.lng] 
    }
}

const confirmLocation = () => {
    if (pendingLocation.value) {
        // Optimistic update
        const newPos = pendingLocation.value
        currentPosition.value = newPos
        
        emit('locationSelect', newPos[0], newPos[1])
        pendingLocation.value = null
    }
}

const cancelLocation = () => {
    pendingLocation.value = null
    // Revert center to saved position
    center.value = currentPosition.value
}
</script>

<template>
  <div class="space-y-4 relative">
    <div class="h-[400px] w-full rounded-lg overflow-hidden border border-gray-300 relative z-0">
      <ClientOnly>
          <l-map
            ref="map"
            v-model:zoom="zoom"
            :center="center"
            :use-global-leaflet="false"
            @click="onMapClick"
            style="cursor: crosshair;"
          >
            <l-tile-layer
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              layer-type="base"
              name="OpenStreetMap"
            ></l-tile-layer>

            <!-- Show current confirmed position -->
             <l-marker v-if="!pendingLocation" :lat-lng="currentPosition"></l-marker>
             <l-circle 
                v-if="!pendingLocation"
                :lat-lng="currentPosition" 
                :radius="radius"
                color="blue"
            ></l-circle>

            <!-- Show pending position -->
            <l-marker v-if="pendingLocation" :lat-lng="pendingLocation"></l-marker>
            <l-circle 
                v-if="pendingLocation"
                :lat-lng="pendingLocation" 
                :radius="radius"
                color="orange"
                dash-array="5, 10"
            ></l-circle>
          </l-map>
      </ClientOnly>

       <!-- Confirmation Modal Overlay -->
        <div v-if="pendingLocation" class="absolute inset-0 z-[1000] flex items-end justify-center pb-6 bg-black/10 pointer-events-none">
             <div class="bg-white p-4 rounded-lg shadow-lg pointer-events-auto flex flex-col items-center gap-3 animate-in fade-in slide-in-from-bottom-4">
                <p class="text-sm font-medium text-gray-900">Update Check Point Location?</p>
                <div class="flex gap-2">
                  <button 
                    @click="cancelLocation"
                    class="px-3 py-1.5 text-xs font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md transition-colors pointer-events-auto"
                  >
                    Cancel
                  </button>
                  <button 
                    @click="confirmLocation"
                    class="px-3 py-1.5 text-xs font-medium text-white bg-brand-navy hover:opacity-90 rounded-md transition-colors pointer-events-auto"
                  >
                    Save Location
                  </button>
                </div>
             </div>
        </div>
    </div>
    <p class="text-xs text-gray-500">
        Click on the map to set the attendance check-point center. You will be asked to confirm.
      </p>
  </div>
</template>
