// pages/[tenant_slug]/dashboard/leaves/periods/create/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useCreateLeavePeriod } from '@/composables/useLeaves'
import { ArrowLeft } from 'lucide-vue-next'
import type { CreateLeavePeriodPayload } from '@/types/leaves'

const router = useRouter()
const route = useRoute()
const tenantSlug = route.params.tenant_slug as string
const { mutate: createPeriod, loading: isPending } = useCreateLeavePeriod()

const form = ref<CreateLeavePeriodPayload>({
    name: '',
    startDate: '',
    endDate: '',
    description: ''
})

const errors = ref<Partial<Record<keyof CreateLeavePeriodPayload, string>>>({})

const validate = () => {
    errors.value = {}
    if (!form.value.name || form.value.name.length < 3) errors.value.name = 'Name is required (min 3 chars)'
    if (!form.value.startDate) errors.value.startDate = 'Start date is required'
    if (!form.value.endDate) errors.value.endDate = 'End date is required'
    return Object.keys(errors.value).length === 0
}

const onSubmit = async () => {
    if (!validate()) return

    try {
        await createPeriod(form.value)
        router.push(`/${tenantSlug}/dashboard/leaves/periods`)
    } catch (e) {
        // Error handled by composable or toast globally if setup
    }
}

definePageMeta({
  layout: 'dashboard'
})
</script>

<template>
    <div class="space-y-6 max-w-2xl mx-auto">
      <div class="flex items-center gap-4">
        <UiButton variant="ghost" @click="router.back()">
          <ArrowLeft class="w-4 h-4 mr-2" /> Back
        </UiButton>
        <h2 className="text-2xl font-bold text-gray-900">Create Leave Period</h2>
      </div>

      <UiCard>
        <UiCardHeader>
          <UiCardTitle>Period Details</UiCardTitle>
        </UiCardHeader>
        <UiCardContent>
          <form @submit.prevent="onSubmit" class="space-y-6">
            <UiInput 
              label="Period Name (e.g. Annual Leave 2025)"
              v-model="form.name"
              :error="errors.name"
            />
            
            <div class="grid grid-cols-2 gap-4">
              <UiInput 
                label="Start Date"
                type="date"
                v-model="form.startDate"
                :error="errors.startDate"
              />
              <UiInput 
                label="End Date"
                type="date"
                v-model="form.endDate"
                :error="errors.endDate"
              />
            </div>

            <div class="space-y-1">
              <label class="text-sm font-medium text-gray-700">Description</label>
              <textarea 
                class="w-full min-h-[100px] border border-gray-300 rounded-md p-2 focus:ring-brand-navy focus:border-brand-navy"
                placeholder="Optional description..."
                v-model="form.description"
              />
            </div>

            <div class="flex justify-end gap-3">
              <UiButton type="button" variant="secondary" @click="router.back()">Cancel</UiButton>
              <UiButton type="submit" :disabled="isPending">
                <span v-if="isPending" class="mr-2">Loading...</span>
                Create Period
              </UiButton>
            </div>
          </form>
        </UiCardContent>
      </UiCard>
    </div>
</template>

// src/app/[tenant_slug]/dashboard/leaves/periods/create/page.tsx
'use client';

import { useCreateLeavePeriod } from '@/hooks/useLeave';
import { CreateLeavePeriodPayload } from '@/types/leave';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { ArrowLeft } from 'lucide-react';
import { useRouter, useParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';

const schema = z.object({
  name: z.string().min(3, 'Name is required'),
  startDate: z.string().min(1, 'Start date is required'),
  endDate: z.string().min(1, 'End date is required'),
  description: z.string().optional(),
});

type FormValues = z.infer<typeof schema>;

export default function CreateLeavePeriodPage() {
  const router = useRouter();
  const params = useParams();
  const tenantSlug = params?.tenant_slug as string;
  const { mutate: createPeriod, isPending } = useCreateLeavePeriod();
  
  const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({
    resolver: zodResolver(schema)
  });

  const onSubmit = (data: FormValues) => {
    createPeriod(data as CreateLeavePeriodPayload, {
      onSuccess: () => router.push(`/${tenantSlug}/dashboard/leaves/periods`)
    });
  };

  return (
    <div className="space-y-6 max-w-2xl mx-auto">
      <div className="flex items-center gap-4">
        <Button variant="ghost" onClick={() => router.back()}>
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>
        <h2 className="text-2xl font-bold text-gray-900">Create Leave Period</h2>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Period Details</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <Input 
              label="Period Name (e.g. Annual Leave 2025)"
              error={errors.name?.message}
              {...register('name')}
            />
            
            <div className="grid grid-cols-2 gap-4">
              <Input 
                label="Start Date"
                type="date"
                error={errors.startDate?.message}
                {...register('startDate')}
              />
              <Input 
                label="End Date"
                type="date"
                error={errors.endDate?.message}
                {...register('endDate')}
              />
            </div>

            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Description</label>
              <textarea 
                className="w-full min-h-[100px] border border-gray-300 rounded-md p-2 focus:ring-brand-navy focus:border-brand-navy"
                placeholder="Optional description..."
                {...register('description')}
              />
              {errors.description && <p className="text-xs text-red-500">{errors.description.message}</p>}
            </div>

            <div className="flex justify-end gap-3">
              <Button type="button" variant="secondary" onClick={() => router.back()}>Cancel</Button>
              <Button type="submit" isLoading={isPending}>Create Period</Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
